spring:
  application:
    name: SumHeart

  config:
    import:
      - optional:file:env/spring.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET_KEY}
    access:
      expiration: ${ACCESS_TIME}
    refresh:
      expiration: ${REFRESH_TIME}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_PROD_REDIRECT_URL}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080
  serverAddress: ${PROD_SERVER_HOST}
  url: ${PROD_SERVER_URL}
  proxy:
    url: ${PROD_PROXY_SERVER_URL}
